Finish integration of Ansible installer
FujitsuEnablingSoftwareTechnologyGmbH/crowbar-openstack pull request #15
Opened 2017-03-01 10:09 UTC by samirjorina

2017-03-13 06:32 UTC, kornicameister commented on crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
> -    %fieldset
I am not enforcing that, but I think I'd keep passwords here.

2017-03-13 09:55 UTC, samirjorina commented on crowbar_framework/app/views/barclamp/monasca/_edit_attributes.html.haml
> -    %fieldset
No idea what would be better...

2017-03-15 12:51 UTC, kornicameister reviewed
Generally, I managed to lunch installer, but there are some issues coming from ansible itself.
Let's try to resolve them first prior to merging that PR

2017-03-16 05:41 UTC, kornicameister requested changes

2017-03-16 05:41 UTC, kornicameister commented on chef/cookbooks/monasca/recipes/master.rb
> +  elasticsearch_hosts: cmm_net_ip
I see no information about keystone_host ?

2017-03-16 05:41 UTC, kornicameister commented on chef/cookbooks/monasca/recipes/master.rb
> +          "&& ansible-playbook -i cmm-hosts -e '#{ansible_vars}' monasca.yml"\
Should cmm-hosts be left in installer directory after install ?

2017-03-16 07:23 UTC, merged