Disable systemd service file creation
FujitsuEnablingSoftwareTechnologyGmbH/crowbar-openstack pull request #19
Opened 2017-03-10 14:13 UTC by witekest

'skip_enable' option controlls the creation of systemd service file for
Monasca Agent. The service file is created in [RPM package](https://review.openstack.org/436063), so the option has to be enabled here.

2017-03-13 06:23 UTC, kornicameister requested changes

2017-03-13 06:23 UTC, kornicameister commented on chef/data_bags/crowbar/template-monasca.json
> +        "skip_enable": true
I wonder if, assuming that service file is created in RPM package, this variable should be added here at all.
Why just not enforce it ?

2017-03-13 10:00 UTC, matrixik commented
Wont it be actually better to overwrite this file every time (every 15 min) `monasca-reconfigure` is run? Then if there are newer version of monasca-agent updated in rpms then it will provide all fixes to service files without need to update them in rpm-packaging (beside updating agent version in spec file).

But if you think it's better to add it only once then I'm fine with it but I think it should be enforced to not overwrite it and not provide option to configure it.

2017-03-13 12:29 UTC, witekest commented
Service configuration files are normally controlled by the RPM package, so I would prefer to keep it there. I will enforce 'skip_enable' option now.

2017-03-13 12:43 UTC, witekest commented on chef/data_bags/crowbar/template-monasca.json
> +        "skip_enable": true
Done.

2017-03-13 19:05 UTC, kornicameister approved these changes

2017-03-14 08:01 UTC, matrixik approved these changes

2017-03-14 08:03 UTC, merged