Configure monasca-server in keystone
FujitsuEnablingSoftwareTechnologyGmbH/crowbar-openstack pull request #5
Opened 2017-01-11 13:42 UTC by samirjorina

2017-01-12 12:53 UTC, matrixik requested changes

2017-01-12 12:53 UTC, matrixik commented on chef/cookbooks/monasca/recipes/server.rb
> +
Too many empty lines

2017-01-12 12:53 UTC, matrixik commented on chef/cookbooks/monasca/recipes/server.rb
> +
Too many empty lines

2017-01-12 12:53 UTC, matrixik commented on chef/cookbooks/monasca/recipes/server.rb
> +register_auth_hash = { user: keystone_settings["admin_user"],
Move `user:...` to next line and align.

2017-01-31 12:22 UTC, matrixik requested changes

2017-01-31 12:22 UTC, matrixik commented on chef/cookbooks/monasca/libraries/helpers.rb
> +module MonascaHelper
Copyright

2017-01-31 12:34 UTC, kornicameister commented on chef/cookbooks/monasca/recipes/role_monasca_server.rb
> +  include_recipe "monasca::api"
If we plan on keeping it that way, I think that should go before monasca::server if the purpose of those recipes is just to register stuff in keystone.

2017-01-31 12:34 UTC, kornicameister commented on chef/cookbooks/monasca/libraries/helpers.rb
> +end
What about log-api ?

2017-02-27 09:09 UTC, closed without merging